module.exports = {
  JWT_SECRET: 'boomarena_secret_2026',
  PORT: 3100,
  GAME_TICK_MS: 50,
  BOMB_FUSE_MS: 3000,
  EXPLOSION_DURATION_MS: 500,
  DEFAULT_MAP_WIDTH: 17,
  DEFAULT_MAP_HEIGHT: 17,
  DEFAULT_PLAYER_COUNT: 4
};
